name: deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 下载源码
      - name: Checkout
        uses: actions/checkout@v4

      # 打包构建
      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: "20.x"
      - run: npm install
      - run: npm run build

      # 部署到 GitHub pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
          publish_dir: ./build/client
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: 自动部署
